# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: trivia knitwear yourself verbal picture sulphur humor basilisk

# Variables to accompany `group_vars/development/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  gnalpp.me:
    admin_password: graffito trident scalp ray aching whom benefit kinsfolk
    env:
      db_password: graffito trident scalp ray aching whom benefit kinsfolk
